Fix macos x86_64 build by raising minimum macos to 10.8
```
The following warnings were emitted during compilation:

warning: clang: warning: include path for libstdc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
warning: In file included from src/cxx.cc:1:
warning: src/../include/cxx.h:2:10: fatal error: 'algorithm' file not found
warning: #include <algorithm>
warning:          ^~~~~~~~~~~
warning: 1 error generated.

error: failed to run custom build command for `cxx v1.0.92`

Caused by:
  process didn't exit successfully: `/Users/runner/work/browsers/browsers/target/release/build/cxx-872eaa5c8a53ad35/build-script-build` (exit status: 1)
  --- stdout
  TARGET = Some("x86_64-apple-darwin")
  OPT_LEVEL = Some("3")
  HOST = Some("x86_64-apple-darwin")
  cargo:rerun-if-env-changed=CXX_x86_64-apple-darwin
  CXX_x86_64-apple-darwin = None
  cargo:rerun-if-env-changed=CXX_x86_64_apple_darwin
  CXX_x86_64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_CXX
  HOST_CXX = None
  cargo:rerun-if-env-changed=CXX
  CXX = None
  cargo:rerun-if-env-changed=CXXFLAGS_x86_64-apple-darwin
  CXXFLAGS_x86_64-apple-darwin = None
  cargo:rerun-if-env-changed=CXXFLAGS_x86_64_apple_darwin
  CXXFLAGS_x86_64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_CXXFLAGS
  HOST_CXXFLAGS = None
  cargo:rerun-if-env-changed=CXXFLAGS
  CXXFLAGS = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2,sse3,ssse3")
  cargo:rerun-if-env-changed=CXX_x86_64-apple-darwin
  CXX_x86_64-apple-darwin = None
  cargo:rerun-if-env-changed=CXX_x86_64_apple_darwin
  CXX_x86_64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_CXX
  HOST_CXX = None
  cargo:rerun-if-env-changed=CXX
  CXX = None
  cargo:rerun-if-env-changed=CXXFLAGS_x86_64-apple-darwin
  CXXFLAGS_x86_64-apple-darwin = None
  cargo:rerun-if-env-changed=CXXFLAGS_x86_64_apple_darwin
  CXXFLAGS_x86_64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_CXXFLAGS
  HOST_CXXFLAGS = None
  cargo:rerun-if-env-changed=CXXFLAGS
  CXXFLAGS = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2,sse3,ssse3")
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-arch" "x86_64" "-Wall" "-Wextra" "-o" "/Users/runner/work/browsers/browsers/target/x86_64-apple-darwin/release/build/cxx-362995a7e77edfde/out/src/cxx.o" "-c" "src/cxx.cc"
  cargo:warning=clang: warning: include path for libstdc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
  cargo:warning=In file included from src/cxx.cc:1:
  cargo:warning=src/../include/cxx.h:2:10: fatal error: 'algorithm' file not found
  cargo:warning=#include <algorithm>
  cargo:warning=         ^~~~~~~~~~~
  cargo:warning=1 error generated.
  exit status: 1

  --- stderr

  error occurred: Command "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-arch" "x86_64" "-Wall" "-Wextra" "-o" "/Users/runner/work/browsers/browsers/target/x86_64-apple-darwin/release/build/cxx-362995a7e77edfde/out/src/cxx.o" "-c" "src/cxx.cc" with args "c++" did not execute successfully (status code exit status: 1).
```